---
repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: go-mod-tidy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/Woile/commitizen
    rev: v1.23.0
    hooks:
      - id: commitizen
        stages: ['commit-msg']
